# Generated by Django 3.0.5 on 2020-06-24 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grupoactividad',
            old_name='sector',
            new_name='prioridad',
        ),
    ]
