# Generated by Django 3.0.5 on 2020-06-25 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0009_auto_20200624_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='grupoactividad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tareas.GrupoActividad'),
        ),
    ]
