# Generated by Django 3.0.5 on 2020-06-26 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0010_auto_20200624_2221'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grupoactividad',
            options={'ordering': ['-nombre']},
        ),
    ]
