# Generated by Django 3.0.5 on 2020-07-07 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0013_auto_20200707_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tareas.Estado'),
        ),
    ]
