# Generated by Django 3.1.2 on 2020-10-16 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0014_auto_20200707_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='comentarios',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
